In [1]:
import pandas as pd

In [2]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [3]:
raw_csv_data.head(5)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [4]:
df = raw_csv_data.copy()

In [5]:
# Helps display every row and column in a data set. 
# This is more applied to larger datasets
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [6]:
display(df)

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,18,10,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,3,11,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10,13,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,20,28,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,11,18,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,10,25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,11,23,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,30,28,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,11,18,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,3,23,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,3,18,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,2,18,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,1,23,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,2,18,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,3,23,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,10,23,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,11,24,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,19,11,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,2,28,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,20,23,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,27,23,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,34,23,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,3,23,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,5,19,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,14,23,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,34,23,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,3,23,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,15,23,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,20,22,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,15,14,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,20,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,29,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,28,23,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,34,23,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,11,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,36,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,28,18,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,3,23,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,13,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,33,23,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,3,23,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,20,23,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,3,23,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,34,23,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,36,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,22,23,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,3,23,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,28,23,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,34,23,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,28,23,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,33,23,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,15,23,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,3,23,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,28,23,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,20,19,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,15,14,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,28,28,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,11,26,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,10,23,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,20,28,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,3,23,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,28,23,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,3,13,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,17,21,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,15,23,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,14,10,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,6,22,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,15,14,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,14,6,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,17,21,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,28,13,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,20,28,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,33,28,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,28,28,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,11,7,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,15,23,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,33,23,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,34,19,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,36,23,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,1,26,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,28,23,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,20,26,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,34,19,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,10,22,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,28,28,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,20,28,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,28,23,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,10,22,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,34,27,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,24,19,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,28,23,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,28,23,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,34,19,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,34,27,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,14,18,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,28,27,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,27,23,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,28,28,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,28,27,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,28,27,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,34,27,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,34,27,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,22,18,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,11,18,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,27,23,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,34,27,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,34,27,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,28,23,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,11,22,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,27,23,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,24,1,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,3,11,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,14,28,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,6,23,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,20,28,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,11,22,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,31,11,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,31,1,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,28,28,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,28,23,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,22,23,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,27,23,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,28,25,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,18,18,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,18,23,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,28,23,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,6,19,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,19,28,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,20,19,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,30,19,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,17,17,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,15,22,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,20,13,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,22,13,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,33,14,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,20,13,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,17,11,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,14,1,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,20,26,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,14,13,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,11,6,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,17,8,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,20,28,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,28,23,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,7,14,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,3,13,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,28,23,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,28,11,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,22,13,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,28,11,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,28,11,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,3,13,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,7,14,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,28,28,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,33,14,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,28,28,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,15,28,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,28,23,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,14,28,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,24,13,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,14,23,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,28,28,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,20,28,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,3,13,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,36,23,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,15,23,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,24,14,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,15,28,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,33,28,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,20,19,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,11,19,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,14,12,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,23,19,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,11,13,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,7,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,2,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,14,28,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,14,28,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,3,18,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,28,19,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,27,7,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,14,28,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,3,12,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,7,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,18,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,23,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,31,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,3,11,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,36,13,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,10,22,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,24,19,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,10,22,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,24,10,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,15,23,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,24,10,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,3,11,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,14,23,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,24,10,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,36,13,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,13,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,36,23,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,36,13,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,23,22,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,3,11,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,32,28,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,28,28,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,14,19,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,36,1,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,34,5,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,34,26,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,18,26,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,22,18,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,14,25,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,18,1,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,18,1,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,30,25,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,10,22,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,11,26,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,3,26,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,11,19,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,11,19,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,20,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,11,19,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,30,19,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,11,23,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,9,18,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,26,13,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,26,14,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,20,28,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,11,23,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,33,23,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,21,11,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,22,23,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,36,13,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,33,25,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,1,23,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,36,23,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,1,19,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,10,8,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,27,6,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,3,11,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,3,23,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,11,19,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,5,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,24,9,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,15,28,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,8,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,19,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,3,13,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,24,9,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,3,23,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,20,28,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,5,26,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,36,28,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,5,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,15,7,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,3,13,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,11,24,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,1,26,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,11,26,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,11,22,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,36,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,33,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,22,1,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,34,7,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,13,22,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,3,28,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,22,1,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,5,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,11,19,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,20,28,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,5,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,36,28,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,15,28,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,22,23,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,36,28,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,10,10,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,20,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,15,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,30,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,22,1,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,22,7,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,36,23,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,34,11,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,33,23,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,3,6,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,20,28,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,15,23,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,23,1,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,14,11,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,5,26,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,18,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,1,18,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,34,11,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,1,25,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,3,28,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,24,13,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,15,12,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,24,13,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,3,28,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,20,10,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,20,15,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,23,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,7,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,3,23,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,28,12,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,1,23,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,36,28,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,20,28,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,24,4,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,3,28,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,3,28,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,22,23,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,34,25,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,1,25,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,3,28,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,5,13,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,14,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,20,26,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,30,28,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,3,28,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,11,19,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,28,23,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,34,19,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,14,23,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,13,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,14,23,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,11,26,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,15,3,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,5,26,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,36,26,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,3,28,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,3,28,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,34,28,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,3,27,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,28,7,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,11,22,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,20,28,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,3,23,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,3,27,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,3,10,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,24,26,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,3,27,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,6,22,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,3
382,24,23,21/02/2017,246,25,41,251.818,23,1,0,0,2
383,15,23,21/02/2017,291,31,40,251.818,25,1,1,1,2
384,30,11,22/02/2017,157,27,29,251.818,22,1,0,0,16
385,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
386,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
387,24,10,24/02/2017,246,25,41,251.818,23,1,0,0,24
388,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
389,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
390,34,18,07/03/2017,118,10,37,244.387,28,1,0,0,8
391,24,19,08/03/2017,246,25,41,244.387,23,1,0,0,16
392,24,28,10/03/2017,246,25,41,244.387,23,1,0,0,2
393,20,28,10/03/2017,260,50,36,244.387,23,1,4,0,4
394,3,28,13/03/2017,179,51,38,244.387,31,1,0,0,2
395,1,22,13/03/2017,235,11,37,244.387,29,3,1,1,8
396,17,22,14/03/2017,179,22,40,244.387,22,2,2,0,8
397,23,22,14/03/2017,378,49,36,244.387,21,1,2,4,8
398,3,28,20/03/2017,179,51,38,244.387,31,1,0,0,16
399,10,22,22/03/2017,361,52,28,244.387,27,1,1,4,8
400,13,0,22/03/2017,369,17,31,244.387,25,1,3,0,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.7+ KB

In [8]:
type(df)

pandas.core.frame.DataFrame

### Drop "ID" Column

In [9]:
df = df.drop(['ID'], axis =1)

In [10]:
df.head(5)

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

## Reasons for Absence column

In [11]:
df['Reason for Absence'].head(5)

0    26
1     0
2    23
3     7
4    23
Name: Reason for Absence, dtype: int64

In [12]:
# print the maximum and min values in our dataframe
df['Reason for Absence'].min(), df['Reason for Absence'].max()

(0, 28)

In [13]:
# print out unique values i our column
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [14]:
# printing the lengthof the unique vales shows us the number of different reasons for absenteesm at work
# In our own case, 28 reasons
len(df['Reason for Absence'].unique())

28

In [15]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [16]:
# sorting the unique valeus allows us to easily spot the missing values in our column
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

## Categorical Nominal Data
Observe that the 'Abssence"column is inputed with numemrical values meaning represnting different reasons in the feature description. However, when applying these values in our model, we'll experience a problem where rreasons with higher values say 20-28 are ranked higher than values below 20. This will go a long way in negatively affecting our model. We adress this problem by introducing dummy variables which gives us a 1 or 0 value for each value of the 'Reason' column

In [17]:
reason_columns = pd.get_dummies(df['Reason for Absence'])
reason_columns.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

We cratet anew column "check" to verify if a particular value is missing in a row

In [18]:
reason_columns['check'] = reason_columns.sum(axis =1)
reason_columns.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,check
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1

In [19]:
# verify that the valeus in our check column is only 1
reason_columns['check'].unique()

array([1])

Being satisfied with the check we can now remove the check column from our dummy variables

In [20]:
reason_columns = reason_columns.drop(['check'], axis =1)
reason_columns.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(9), object(1)
memory usage: 60.2+ KB

In order to avoid multicollinearity issues, we drop the "Reason 0" column).

In [22]:
# Drop first column
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True)
reason_columns.head(2)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Group the Reasons for Absence

Since we have too many coluns for analysis, we group the various reasons for absence to make things easy

In [23]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [24]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [25]:
df = df.drop(['Reason for Absence'], axis=1)

In [26]:
df.head(2)

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0

The process of re-organizing/grouping a certain type of vaiables into groups in a regression analysis can be called regression analysis

In [27]:
reason_columns.loc[:, 1:14].max(axis=1).head(15)

0     0
1     0
2     0
3     1
4     0
5     0
6     0
7     0
8     0
9     0
10    1
11    1
12    1
13    1
14    0
dtype: uint8

In [28]:
# Let's group our dummy variabes based on similar reasons
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

In [29]:
reason_type_1.head(5)

0    0
1    0
2    0
3    1
4    0
dtype: uint8

## Concatenate Column Values

In [30]:
df.head(2)

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0

In [31]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis=1)

In [32]:
df.head(2)

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0

In [33]:
# Assign column names to the new columns
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [34]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1','Reason_2', 'Reason_3', 'Reason_4']

In [35]:
df.columns = column_names

In [36]:
df.head(1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
dtypes: float64(1), int64(8), object(1), uint8(4)
memory usage: 57.5+ KB

## Reordering Columns

In [37]:
column_names_reorder = ['Reason_1','Reason_2', 'Reason_3', 'Reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets', 'Absenteeism Time in Hours'] 
df = df[column_names_reorder]
df.head(1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(8), object(1), uint8(4)
memory usage: 57.5+ KB

## Creat a Checkpoint
Creating checkpoints allows us store the current version of our work

In [38]:
df_reason_mod = df.copy()

In [39]:
df_reason_mod.head(5)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

Now that we've created our checkpoint, we'll keep using the new df_reason_mod dataframe and preserve the old df dataframe. We can always fall back to the initial df dataframe should we encounter problems along the way.

## Workinng on the Date Column

In [40]:
df_reason_mod['Date'].head()

0    07/07/2015
1    14/07/2015
2    15/07/2015
3    16/07/2015
4    23/07/2015
Name: Date, dtype: object

In [41]:
# Check for data type
# Every dataframe column comes as a Series data type.
type(df_reason_mod['Date'])

pandas.core.series.Series

In [42]:
# However, our column values still maintain their data types
type(df_reason_mod['Date'][0])

str

In [43]:
# we convert the date column type to a time stamp
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'])

In [44]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [45]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [46]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [47]:
type(df_reason_mod['Date'])

pandas.core.series.Series

In [48]:
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [49]:
# Extract the MOnth value
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [50]:
df_reason_mod['Date'][0].month

7

In [51]:
df_reason_mod.shape

(700, 14)

In [52]:
list_months =[]
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)
    
    
list_months

[7,
 7,
 7,
 7,
 7,
 10,
 7,
 7,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 12,
 3,
 10,
 8,
 8,
 8,
 4,
 12,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 4,
 8,
 8,
 8,
 1,
 7,
 1,
 8,
 9,
 9,
 9,
 9,
 4,
 9,
 9,
 9,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 11,
 9,
 9,
 6,
 10,
 10,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 4,
 5,
 12,
 11,
 2,
 9,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 2,
 10,
 11,
 11,
 1,
 1,
 2,
 2,
 3,
 4,
 8,
 9,
 10,
 11,
 12,
 12,
 11,
 12,
 12,
 6,
 4,
 5,
 5,
 6,
 7,
 7,
 8,
 11,
 12,
 12,
 1,
 1,
 1,
 11,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 3,
 10,
 11,
 11,
 12,
 12,
 8,
 9,
 2,
 9,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 8,
 3,
 3,
 2,
 3,
 4,
 4,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 4,
 12,
 4,
 4,
 4,
 4,
 6,
 7,
 8,
 8,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 8,
 4,
 4,
 5,
 2,
 3,
 3,
 11,
 9,
 10,
 4,
 11,
 5,
 5,
 5,
 5,
 11,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 3,
 7,
 8,
 9,
 10,
 6,
 6,
 5,
 6,
 8,
 8,
 12,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 11,
 7,
 7,
 4,
 11,
 7,
 8,
 10,
 10,
 11,
 8,
 9,
 10,
 10,
 10,
 8,
 8,
 8,
 8,
 8,
 8,
 5,
 9,
 7,
 8,
 12,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 5,
 5,
 5,
 6,
 6,
 6,
 12,
 12,
 12,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 7,
 8,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 5,
 5,
 5,
 5,
 6,
 9,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 4,
 9,
 9,
 3,
 3,
 9,
 11,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 3,
 10,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 7,
 8,
 10,
 10,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 7,
 7,
 10,
 10,
 12,
 12,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 3,
 8,
 10,
 10,
 11,
 12,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 8,
 9,
 9,
 12,
 12,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 10,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 3,
 7,
 8,
 8,
 8,
 8,
 10,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 5,
 5,
 5,
 5,
 7,
 8,
 8,
 11,
 9,
 9,
 9,
 9,
 5,
 5,
 6,
 11,
 11,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 7,
 8,
 8,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 5,
 6,
 6,
 8,
 8,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 4,
 4,
 5,
 8,
 10,
 11,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 6,
 6,
 7,
 7,
 8,
 8,
 8,
 9,
 9,
 12,
 12,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 6,
 6,
 6,
 7,
 8,
 8,
 8,
 9,
 12,
 12,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 4,
 5,
 6,
 9,
 10,
 10,
 10,
 11,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 7,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 11,
 11,
 11,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5]

In [53]:
# let's verify if the all our values are included
len(list_months)

700

In [54]:
df_reason_mod['Month Values'] = list_months

In [55]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Values
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7

## Extract the Day of the Week

In [56]:
df_reason_mod['Date'][3].weekday()

3

In [57]:
df_reason_mod['Date'][3]

Timestamp('2015-07-16 00:00:00')

In [58]:
# we create  function that extracts days of the week 
def day_of_week(date_value):
    return date_value.weekday()

In [59]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(day_of_week)

In [60]:
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Values,Day of the Week
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

## Dropping the Date Column

In [61]:
df_reason_mod =  df_reason_mod.drop(['Date'], axis =1)

In [62]:
df_reason_mod.head()
df_reason_mod.shape

(700, 15)

In [63]:
col_m = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
        'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Values', 'Day of the Week']

In [64]:
df_reason_mod.columns = col_m
df_reason_mod.head()
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
Reason_1                     700 non-null uint8
Reason_2                     700 non-null uint8
Reason_3                     700 non-null uint8
Reason_4                     700 non-null uint8
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
Month Values                 700 non-null int64
Day of the Week              700 non-null int64
dtypes: float64(1), int64(10), uint8(4)
memory usage: 63.0 KB

In [65]:
# Let's reorder our columns by bringing the newly created ones at the date column position
columns_mod = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values', 'Day of the Week','Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education','Children', 'Pets', 'Absenteeism Time in Hours']

In [66]:
df_reason_mod = df_reason_mod[columns_mod]
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

## Checkpoint

In [67]:
df_reason_date_mod = df_reason_mod.copy()

In [68]:
df_reason_date_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

## Analyzing the Next 5 Columns

In [69]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [70]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [71]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [72]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

In [73]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

The above 5 columns are are in a good state and will be highly useful to our model

## 'Educaton', 'Children', 'Pets'
Education columns has categorical variables, we'll take time to explore them one after the other.

In [74]:
df_reason_date_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

In [75]:
# let's check the unique valeus under the education column
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4])

In [76]:
# Let's check educational qualification with the highest number of staff
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64


From the data dictionary, we learnt that:

1 ---- High Schoo

2 --- Graduate

3 ---- PG

4 ---- A masters or Doctorate

Since the proportion between 2,3&4 is not much, We shall map them under a single category

In [77]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [78]:
df_reason_date_mod['Education'].unique()

array([0, 1])

In [79]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

## Final Checkpoint

In [80]:
df_processed = df_reason_date_mod.copy()
df_processed.head(15)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,10,2,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4
8,0,0,1,0,6,6,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8
10,1,0,0,0,7,0,260,50,36,239.554,23,0,4,0,8
11,1,0,0,0,7,1,260,50,36,239.554,23,0,4,0,8
12,1,0,0,0,7,2,260,50,36,239.554,23,0,4,0,8
13,1,0,0,0,7,2,179,51,38,239.554,31,0,0,0,1
14,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,4

In [81]:
df_processed.to_csv('Absenteeism_processed.csv', index=False)

## Machine Learning
### creating a Logistic Regresson

In [82]:
import numpy as np

In [83]:
# we eyeball our data
df_processed.head(10)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,10,2,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4
8,0,0,1,0,6,6,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8

## create the target
For this task, we'll be classifying peopl into classes. **Moderately Absent** and **Excessively Absent**
We take the mean value of the target cell. Anythign above he median will be excessive, anythig below he median will be normal

In [84]:
# We find the median
df_processed['Absenteeism Time in Hours'].median()

3.0

In [85]:
#Where column> median =1 else =0
target = np.where(df_processed['Absenteeism Time in Hours']>df_processed['Absenteeism Time in Hours'].median(),1,0)

In [86]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [87]:
# we add the new colun to our data
df_processed['Excessive_Absenteeism'] = target

In [88]:
df_processed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive_Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

## A comment on the targets

In [89]:
# we'll see that roughly half of the targets are zeros while the rest 1s
target.sum()/target.shape[0]

0.45571428571428574

The value above shows that abut 46% of the targets are 1s leaving about 54% as 0s.

In [90]:
data_with_targets = df_processed.drop(['Absenteeism Time in Hours', 'Education', 'Pets', 'Age'], axis =1)

In [91]:
# let's check if the two variables are same using a new technique
data_with_targets is df_processed

False

## Select the inputs for regression

In [92]:
data_with_targets.shape

(700, 12)

In [93]:
data_with_targets.iloc[:, :-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Children
0,0,0,0,1,7,1,289,36,239.554,30,2
1,0,0,0,0,7,1,118,13,239.554,31,1
2,0,0,0,1,7,2,179,51,239.554,31,0
3,1,0,0,0,7,3,279,5,239.554,24,2
4,0,0,0,1,7,3,289,36,239.554,30,2
5,0,0,0,1,10,2,179,51,239.554,31,0
6,0,0,0,1,7,4,361,52,239.554,27,1
7,0,0,0,1,7,4,260,50,239.554,23,4
8,0,0,1,0,6,6,155,12,239.554,25,2
9,0,0,0,1,7,0,235,11,239.554,29,1
10,1,0,0,0,7,0,260,50,239.554,23,4
11,1,0,0,0,7,1,260,50,239.554,23,4
12,1,0,0,0,7,2,260,50,239.554,23,4
13,1,0,0,0,7,2,179,51,239.554,31,0
14,0,0,0,1,7,2,179,51,239.554,31,0
15,1,0,0,0,7,4,246,25,239.554,23,0
16,0,0,0,1,7,4,179,51,239.554,31,0
17,0,0,1,0,7,0,179,51,239.554,31,0
18,1,0,0,0,7,3,189,29,239.554,25,2
19,0,0,0,1,5,4,248,25,205.917,32,2
20,1,0,0,0,12,1,330,16,205.917,25,0
21,1,0,0,0,3,6,179,51,205.917,31,0
22,1,0,0,0,10,3,361,52,205.917,27,1
23,0,0,0,1,8,4,260,50,205.917,23,4
24,0,0,1,0,8,0,289,36,205.917,30,2
25,0,0,0,1,8,0,361,52,205.917,27,1
26,0,0,0,1,4,2,289,36,205.917,30,2
27,0,0,0,1,12,1,157,27,205.917,22,0
28,0,0,1,0,8,2,289,36,205.917,30,2
29,0,0,0,1,8,4,179,51,205.917,31,0
30,0,0,1,0,8,0,179,51,205.917,31,0
31,0,0,1,0,8,3,235,29,205.917,33,1
32,0,0,0,1,8,3,235,11,205.917,29,1
33,0,0,1,0,8,0,235,29,205.917,33,1
34,0,0,0,1,8,0,179,51,205.917,31,0
35,0,0,0,1,8,0,361,52,205.917,27,1
36,0,0,0,1,4,2,289,36,205.917,30,2
37,1,0,0,0,8,3,291,50,205.917,23,0
38,0,0,0,1,8,4,235,29,205.917,33,1
39,0,0,0,1,8,4,260,50,205.917,23,4
40,0,0,0,1,1,4,184,42,241.476,21,0
41,0,0,0,1,7,3,118,10,241.476,28,0
42,0,0,0,1,1,4,179,51,241.476,31,0
43,0,0,1,0,8,6,235,20,241.476,38,1
44,0,0,0,1,9,2,155,12,241.476,25,2
45,0,0,0,1,9,6,118,10,241.476,28,0
46,0,0,0,1,9,0,179,51,241.476,31,0
47,0,0,0,1,9,3,291,31,241.476,25,1
48,0,0,0,1,4,3,260,50,241.476,23,4
49,1,0,0,0,9,0,291,31,241.476,25,1
50,0,0,0,0,9,0,260,50,241.476,23,4
51,0,0,0,0,9,0,225,26,241.476,24,1
52,0,0,0,1,8,6,225,26,241.476,24,1
53,0,0,0,1,9,1,118,10,241.476,28,0
54,0,0,0,0,9,1,289,36,241.476,30,2
55,0,0,0,0,9,1,118,13,241.476,31,1
56,0,0,1,0,9,2,225,26,241.476,24,1
57,0,0,0,1,9,2,179,51,241.476,31,0
58,0,0,0,0,9,2,369,17,241.476,25,3
59,0,0,0,1,11,0,248,25,241.476,32,2
60,0,0,0,1,9,4,179,51,241.476,31,0
61,0,0,0,1,9,4,260,50,241.476,23,4
62,0,0,0,1,6,2,179,51,253.465,31,0
63,0,0,0,1,10,1,118,10,253.465,28,0
64,0,0,0,0,10,2,118,13,253.465,31,1
65,0,0,0,1,10,3,179,26,253.465,19,0
66,0,0,0,1,10,4,179,51,253.465,31,0
67,0,0,0,1,10,4,225,26,253.465,24,1
68,0,0,0,1,6,2,118,10,253.465,28,0
69,0,0,0,1,10,2,225,26,253.465,24,1
70,0,0,0,1,10,2,248,25,253.465,32,2
71,0,0,0,1,10,3,291,31,253.465,25,1
72,0,0,0,1,10,2,179,51,253.465,31,0
73,0,0,0,1,10,2,225,26,253.465,24,1
74,0,0,1,0,10,3,260,50,253.465,23,4
75,1,0,0,0,10,1,291,31,253.465,25,1
76,0,0,0,1,10,1,225,26,253.465,24,1
77,0,0,0,1,10,2,289,36,253.465,30,2
78,0,0,0,1,10,4,361,52,253.465,27,1
79,0,0,0,1,10,4,260,50,253.465,23,4
80,0,0,0,1,5,0,179,51,306.345,31,0
81,0,0,0,1,4,5,225,26,306.345,24,1
82,1,0,0,0,5,0,179,51,306.345,31,0
83,0,0,1,0,12,4,179,22,306.345,22,2
84,0,0,0,1,11,3,291,31,306.345,25,1
85,1,0,0,0,2,2,155,12,306.345,25,2
86,0,0,0,1,9,4,189,29,306.345,25,2
87,1,0,0,0,11,0,291,31,306.345,25,1
88,0,0,0,1,11,2,225,26,306.345,24,1
89,1,0,0,0,11,4,155,12,306.345,25,2
90,0,0,0,1,11,2,225,26,306.345,24,1
91,0,0,1,0,11,2,179,22,306.345,22,2
92,1,0,0,0,11,4,225,26,306.345,24,1
93,0,0,0,1,11,4,260,50,306.345,23,4
94,0,0,0,1,2,2,248,25,306.345,32,2
95,0,0,0,1,10,6,225,26,306.345,24,1
96,1,0,0,0,11,2,289,36,306.345,30,2
97,0,0,0,1,11,3,291,31,306.345,25,1
98,0,0,0,1,1,0,248,25,261.306,32,2
99,0,0,1,0,1,0,118,10,261.306,28,0
100,0,0,0,1,2,3,118,13,261.306,31,1
101,0,0,0,1,2,3,235,11,261.306,29,1
102,0,0,0,1,3,3,225,26,261.306,24,1
103,0,0,0,1,4,6,260,50,261.306,23,4
104,0,0,1,0,8,2,118,10,261.306,28,0
105,0,0,0,1,9,5,361,52,261.306,27,1
106,0,0,0,1,10,0,225,26,261.306,24,1
107,0,0,0,1,11,3,260,50,261.306,23,4
108,0,0,0,1,12,1,225,26,261.306,24,1
109,0,0,0,1,12,2,361,52,261.306,27,1
110,0,0,0,1,11,3,118,10,261.306,28,0
111,0,0,1,0,12,4,246,25,261.306,23,0
112,0,0,0,1,12,4,225,26,261.306,24,1
113,0,0,0,1,6,2,225,26,308.593,24,1
114,0,0,1,0,4,4,118,10,308.593,28,0
115,0,0,0,1,5,6,118,10,308.593,28,0
116,0,0,1,0,5,6,155,12,308.593,25,2
117,0,0,0,1,6,2,225,26,308.593,24,1
118,0,0,0,1,7,4,184,42,308.593,21,0
119,0,0,0,1,7,4,225,26,308.593,24,1
120,0,0,0,1,8,0,225,26,308.593,24,1
121,0,0,0,1,11,1,118,10,308.593,28,0
122,0,0,0,1,12,3,225,26,308.593,24,1
123,0,0,0,1,12,3,118,10,308.593,28,0
124,0,0,0,1,1,2,118,10,308.593,28,0
125,0,0,0,1,1,3,118,10,308.593,28,0
126,0,0,0,1,1,4,118,10,308.593,28,0
127,0,0,0,1,11,1,118,10,308.593,28,0
128,0,0,0,1,12,3,118,10,308.593,28,0
129,0,0,1,0,12,3,179,26,308.593,19,0
130,0,0,1,0,12,3,289,36,308.593,30,2
131,0,0,0,1,1,2,118,10,308.593,28,0
132,0,0,0,1,1,3,184,42,308.593,21,0
133,0,0,0,1,1,3,118,10,308.593,28,0
134,0,0,0,1,1,0,118,10,308.593,28,0
135,0,0,0,1,1,1,225,26,308.593,24,1
136,0,0,0,1,1,3,289,36,308.593,30,2
137,0,0,0,1,5,0,184,42,302.585,21,0
138,1,0,0,0,3,2,246,25,302.585,23,0
139,1,0,0,0,10,6,179,51,302.585,31,0
140,0,0,0,1,11,2,155,12,302.585,25,2
141,0,0,0,1,11,2,189,29,302.585,25,2
142,0,0,0,1,12,4,260,50,302.585,23,4
143,0,0,0,1,12,4,289,36,302.585,30,2
144,1,0,0,0,8,1,388,15,302.585,24,0
145,1,0,0,0,9,4,388,15,302.585,24,0
146,0,0,0,1,2,0,225,26,302.585,24,1
147,0,0,0,1,9,4,225,26,302.585,24,1
148,0,0,0,1,2,1,179,26,302.585,19,0
149,0,0,0,1,2,1,184,42,302.585,21,0
150,0,0,0,1,2,3,225,26,302.585,24,1
151,0,0,1,0,2,0,330,16,302.585,25,0
152,0,0,0,1,2,1,330,16,302.585,25,0
153,0,0,0,1,2,2,225,26,302.585,24,1
154,0,0,1,0,2,3,189,29,302.585,25,2
155,0,0,0,1,1,6,291,50,343.253,23,0
156,0,0,1,0,1,6,260,50,343.253,23,4
157,0,0,1,0,8,2,157,27,343.253,22,0
158,0,1,0,0,3,1,179,22,343.253,22,2
159,0,0,0,1,3,2,291,31,343.253,25,1
160,1,0,0,0,2,2,260,50,343.253,23,4
161,1,0,0,0,3,3,179,26,343.253,19,0
162,1,0,0,0,4,6,248,25,343.253,32,2
163,1,0,0,0,4,6,260,50,343.253,23,4
164,1,0,0,0,7,6,179,22,343.253,22,2
165,1,0,0,0,3,0,155,12,343.253,25,2
166,0,0,0,1,3,0,260,50,343.253,23,4
167,1,0,0,0,3,1,155,12,343.253,25,2
168,1,0,0,0,3,3,289,36,343.253,30,2
169,1,0,0,0,3,3,179,22,343.253,22,2
170,0,0,0,1,3,4,260,50,343.253,23,4
171,0,0,0,1,3,4,225,26,343.253,24,1
172,1,0,0,0,3,0,279,5,343.253,24,2
173,1,0,0,0,3,1,179,51,343.253,31,0
174,0,0,0,1,3,2,225,26,343.253,24,1
175,1,0,0,0,3,0,225,26,343.253,24,1
176,1,0,0,0,3,0,179,26,343.253,19,0
177,1,0,0,0,3,1,225,26,343.253,24,1
178,1,0,0,0,3,2,225,26,343.253,24,1
179,1,0,0,0,3,2,179,51,343.253,31,0
180,1,0,0,0,3,3,279,5,343.253,24,2
181,0,0,0,1,3,4,225,26,343.253,24,1
182,1,0,0,0,3,4,248,25,343.253,32,2
183,0,0,0,1,3,0,225,26,343.253,24,1
184,0,0,0,1,6,5,291,31,326.452,25,1
185,0,0,0,1,4,2,225,26,326.452,24,1
186,0,0,0,1,12,6,155,12,326.452,25,2
187,1,0,0,0,4,2,246,25,326.452,23,0
188,0,0,0,1,4,3,155,12,326.452,25,2
189,0,0,0,1,4,4,225,26,326.452,24,1
190,0,0,0,1,4,4,260,50,326.452,23,4
191,1,0,0,0,6,5,179,51,326.452,31,0
192,0,0,0,1,7,0,118,13,326.452,31,1
193,0,0,0,1,8,3,291,31,326.452,25,1
194,1,0,0,0,8,3,246,25,326.452,23,0
195,0,0,0,1,4,4,291,31,326.452,25,1
196,0,0,0,1,4,4,248,25,326.452,32,2
197,0,0,1,0,4,4,260,50,326.452,23,4
198,0,0,1,0,4,1,289,36,326.452,30,2
199,1,0,0,0,4,2,155,12,326.452,25,2
200,0,0,1,0,4,2,378,49,326.452,21,2
201,1,0,0,0,4,3,289,36,326.452,30,2
202,1,0,0,0,8,3,235,11,326.452,29,1
203,0,0,0,0,4,0,235,29,326.452,33,1
204,1,0,0,0,4,1,289,36,378.884,30,2
205,0,0,0,1,5,3,155,12,378.884,25,2
206,0,0,0,1,2,4,155,12,378.884,25,2
207,0,0,1,0,3,5,179,51,378.884,31,0
208,0,0,1,0,3,5,225,26,378.884,24,1
209,1,0,0,0,11,5,184,42,378.884,21,0
210,0,0,0,1,9,0,155,12,378.884,25,2
211,1,0,0,0,10,2,179,51,378.884,31,0
212,1,0,0,0,4,1,289,36,378.884,30,2
213,0,0,0,0,11,5,279,5,378.884,24,2
214,0,0,0,0,5,2,330,16,378.884,25,0
215,0,0,0,0,5,2,378,49,378.884,21,2
216,0,0,0,0,5,2,388,15,378.884,24,0
217,1,0,0,0,5,1,179,51,378.884,31,0
218,1,0,0,0,11,5,118,13,378.884,31,1
219,0,0,0,1,5,4,361,52,378.884,27,1
220,0,0,1,0,6,0,246,25,377.550,23,0
221,0,0,0,1,6,0,361,52,377.550,27,1
222,1,0,0,0,6,1,246,25,377.550,23,0
223,0,0,0,1,6,3,291,31,377.550,25,1
224,1,0,0,0,6,4,246,25,377.550,23,0
225,1,0,0,0,6,0,179,51,377.550,31,0
226,0,0,0,1,6,0,155,12,377.550,25,2
227,1,0,0,0,6,0,246,25,377.550,23,0
228,1,0,0,0,6,2,118,13,377.550,31,1
229,1,0,0,0,3,6,235,11,377.550,29,1
230,0,0,0,1,7,2,118,13,377.550,31,1
231,1,0,0,0,8,5,118,13,377.550,31,1
232,0,0,0,1,9,1,378,49,377.550,21,2
233,1,0,0,0,10,3,179,51,377.550,31,0
234,0,0,0,1,6,0,289,48,377.550,36,0
235,0,0,0,1,6,3,225,26,377.550,24,1
236,0,0,1,0,5,5,155,12,275.312,25,2
237,1,0,0,0,6,1,118,13,275.312,31,1
238,1,0,0,0,8,6,118,10,275.312,28,0
239,0,0,0,1,8,6,118,10,275.312,28,0
240,0,0,0,1,12,2,330,16,275.312,25,0
241,0,0,1,0,7,3,179,26,275.312,19,0
242,0,0,0,1,7,4,155,12,275.312,25,2
243,1,0,0,0,7,0,330,16,275.312,25,0
244,1,0,0,0,7,1,330,16,275.312,25,0
245,0,0,0,1,7,0,157,27,275.312,22,0
246,0,0,0,1,7,1,361,52,275.312,27,1
247,0,0,0,1,7,2,289,36,275.312,30,2
248,0,0,0,1,7,3,179,51,275.312,31,0
249,0,0,1,0,11,0,289,36,275.312,30,2
250,0,0,1,0,7,3,289,36,275.312,30,2
251,0,0,0,0,7,3,260,50,275.312,23,4
252,0,0,1,0,4,4,289,36,265.615,30,2
253,0,0,1,0,11,1,157,27,265.615,22,0
254,0,0,0,1,7,4,289,36,265.615,30,2
255,0,0,1,0,8,0,228,14,265.615,22,2
256,1,0,0,0,10,5,300,26,265.615,25,2
257,1,0,0,0,10,5,300,26,265.615,25,2
258,0,0,0,1,11,1,260,50,265.615,23,4
259,0,0,0,1,8,0,289,36,265.615,30,2
260,0,0,0,1,9,3,248,25,265.615,32,2
261,1,0,0,0,10,5,268,11,265.615,25,0
262,0,0,0,1,10,5,179,26,265.615,19,0
263,1,0,0,0,10,5,118,13,265.615,31,1
264,0,0,0,1,8,6,248,25,265.615,32,2
265,0,0,0,1,8,0,235,11,265.615,29,1
266,0,0,0,1,8,2,118,13,265.615,31,1
267,0,0,1,0,8,2,235,11,265.615,29,1
268,1,0,0,0,8,0,361,52,265.615,27,1
269,1,0,0,0,8,1,184,42,265.615,21,0
270,1,0,0,0,5,0,179,51,294.217,31,0
271,0,0,0,1,9,4,179,51,294.217,31,0
272,0,0,1,0,7,5,289,36,294.217,30,2
273,0,0,0,0,8,1,235,20,294.217,38,1
274,1,0,0,0,12,4,246,25,294.217,23,0
275,0,0,0,1,9,1,291,31,294.217,25,1
276,0,0,0,0,9,1,231,35,294.217,35,2
277,0,0,0,0,9,1,291,50,294.217,23,0
278,1,0,0,0,9,2,179,51,294.217,31,0
279,1,0,0,0,9,2,246,25,294.217,23,0
280,0,0,0,1,9,3,179,51,294.217,31,0
281,0,0,0,1,9,4,291,31,294.217,25,1
282,0,0,0,1,9,4,260,50,294.217,23,4
283,0,0,0,1,9,2,235,20,294.217,38,1
284,0,0,0,1,9,3,118,13,294.217,31,1
285,0,0,0,0,9,3,235,20,294.217,38,1
286,0,0,0,1,9,4,291,31,294.217,25,1
287,1,0,0,0,9,0,291,31,294.217,25,1
288,1,0,0,0,9,0,179,51,294.217,31,0
289,0,0,0,1,5,1,289,36,265.017,30,2
290,0,0,0,1,5,1,235,11,265.017,29,1
291,0,0,0,1,5,1,289,36,265.017,30,2
292,0,0,0,1,6,4,289,36,265.017,30,2
293,0,0,0,0,6,4,118,13,265.017,31,1
294,0,0,0,0,6,4,248,25,265.017,32,2
295,1,0,0,0,12,5,179,26,265.017,19,0
296,1,0,0,0,12,5,118,10,265.017,28,0
297,0,0,0,1,12,5,369,17,265.017,25,3
298,0,0,0,1,10,4,179,51,265.017,31,0
299,1,0,0,0,10,4,179,26,265.017,19,0
300,0,0,0,0,10,4,235,20,265.017,38,1
301,0,0,1,0,10,5,289,36,265.017,30,2
302,0,0,0,1,10,6,260,50,265.017,23,4
303,0,0,0,0,10,6,235,20,265.017,38,1
304,0,0,0,1,10,2,235,20,265.017,38,1
305,0,0,0,1,10,2,235,20,265.017,38,1
306,0,0,0,1,10,3,118,13,265.017,31,1
307,0,0,0,1,10,3,291,31,265.017,25,1
308,0,0,0,1,10,5,179,26,265.017,19,0
309,0,0,0,1,10,5,118,13,265.017,31,1
310,1,0,0,0,10,2,361,52,265.017,27,1
311,0,0,0,0,10,3,260,50,265.017,23,4
312,0,0,0,0,10,3,291,31,265.017,25,1
313,0,0,0,0,10,3,157,27,265.017,22,0
314,1,0,0,0,10,4,179,26,265.017,19,0
315,1,0,0,0,10,4,179,26,265.017,19,0
316,0,0,0,1,10,5,118,13,265.017,31,1
317,1,0,0,0,7,0,118,10,284.031,28,0
318,0,0,0,1,7,0,248,25,284.031,32,2
319,1,0,0,0,8,3,179,51,284.031,31,0
320,0,0,0,1,11,4,260,50,284.031,23,4
321,0,0,0,1,11,0,291,31,284.031,25,1
322,1,0,0,0,11,0,378,49,284.031,21,2
323,1,0,0,0,11,0,155,12,284.031,25,2
324,0,0,0,1,11,0,235,20,284.031,38,1
325,0,0,0,0,11,1,330,16,284.031,25,0
326,0,0,1,0,11,2,235,11,284.031,29,1
327,1,0,0,0,11,2,118,10,284.031,28,0
328,0,0,0,1,11,3,235,11,284.031,29,1
329,0,0,0,1,11,3,179,51,284.031,31,0
330,1,0,0,0,11,4,246,25,284.031,23,0
331,1,0,0,0,11,4,291,31,284.031,25,1
332,1,0,0,0,11,0,246,25,284.031,23,0
333,0,0,0,1,11,1,179,51,284.031,31,0
334,1,0,0,0,11,2,260,50,284.031,23,4
335,0,1,0,0,11,4,260,50,284.031,23,4
336,0,0,0,0,11,4,378,49,284.031,21,2
337,0,0,0,0,11,1,279,5,284.031,24,2
338,0,0,0,1,11,3,179,51,284.031,31,0
339,1,0,0,0,5,3,225,26,236.629,24,1
340,0,0,0,1,5,3,179,51,236.629,31,0
341,0,0,0,1,5,3,179,51,236.629,31,0
342,0,0,0,1,5,3,235,11,236.629,29,1
343,0,0,0,1,6,6,118,13,236.629,31,1
344,0,0,0,1,9,0,260,50,236.629,23,4
345,1,0,0,0,12,3,246,25,236.629,23,0
346,0,0,0,1,12,3,179,51,236.629,31,0
347,0,0,0,1,12,4,179,51,236.629,31,0
348,0,0,0,1,12,1,179,26,236.629,19,0
349,0,0,0,1,12,1,118,10,236.629,28,0
350,0,0,0,1,12,3,235,11,236.629,29,1
351,0,0,0,1,12,4,179,51,236.629,31,0
352,1,0,0,0,12,1,235,20,236.629,38,1
353,1,0,0,0,12,1,235,11,236.629,29,1
354,0,0,0,1,12,2,260,50,236.629,23,4
355,0,0,0,1,12,0,157,27,236.629,22,0
356,0,0,0,1,12,0,179,51,236.629,31,0
357,0,0,1,0,12,0,289,36,236.629,30,2
358,0,0,0,1,4,5,225,26,330.061,24,1
359,0,0,1,0,9,4,118,10,330.061,28,0
360,0,0,0,1,9,4,155,12,330.061,25,2
361,1,0,0,0,3,2,235,11,330.061,29,1
362,0,0,0,1,3,2,155,12,330.061,25,2
363,0,0,0,1,9,4,289,36,330.061,30,2
364,1,0,0,0,11,2,291,31,330.061,25,1
365,0,0,0,1,1,0,235,20,330.061,38,1
366,0,0,0,1,1,0,118,13,330.061,31,1
367,0,0,0,1,1,2,179,51,330.061,31,0
368,0,0,0,1,1,4,179,51,330.061,31,0
369,0,0,0,1,7,6,118,10,251.818,28,0
370,0,0,0,1,1,0,179,51,251.818,31,0
371,1,0,0,0,1,0,225,26,251.818,24,1
372,0,0,0,1,3,3,289,36,251.818,30,2
373,0,0,0,1,10,0,260,50,251.818,23,4
374,0,0,0,1,2,4,179,51,251.818,31,0
375,0,0,0,1,2,0,179,51,251.818,31,0
376,0,0,0,1,2,2,179,51,251.818,31,0
377,1,0,0,0,2,3,179,51,251.818,31,0
378,0,0,0,1,2,3,246,25,251.818,23,0
379,0,0,0,1,2,4,179,51,251.818,31,0
380,0,0,0,1,2,0,189,29,251.818,25,2
381,0,0,0,1,2,0,179,51,251.818,31,0
382,0,0,0,1,2,1,246,25,251.818,23,0
383,0,0,0,1,2,1,291,31,251.818,25,1
384,1,0,0,0,2,2,157,27,251.818,22,0
385,0,0,0,1,2,2,179,51,251.818,31,0
386,0,0,0,1,2,4,179,51,251.818,31,0
387,1,0,0,0,2,4,246,25,251.818,23,0
388,0,0,0,1,2,2,179,51,251.818,31,0
389,0,0,0,1,2,4,179,51,251.818,31,0
390,0,0,1,0,7,0,118,10,244.387,28,0
391,0,0,1,0,8,3,246,25,244.387,23,0
392,0,0,0,1,10,1,246,25,244.387,23,0
393,0,0,0,1,10,1,260,50,244.387,23,4
394,0,0,0,1,3,0,179,51,244.387,31,0
395,0,0,0,1,3,0,235,11,244.387,29,1
396,0,0,0,1,3,1,179,22,244.387,22,2
397,0,0,0,1,3,1,378,49,244.387,21,2
398,0,0,0,1,3,0,179,51,244.387,31,0
399,0,0,0,1,3,2,361,52,244.387,27,1
400,0,0,0,0,3,2,369,17,244.387,25,3
401,0,0,1,0,3,3,235,11,244.387,29,1
402,0,0,0,1,3,4,118,13,244.387,31,1
403,1,0,0,0,3,1,118,13,244.387,31,1
404,1,0,0,0,3,2,118,13,244.387,31,1
405,0,0,0,0,3,3,235,11,244.387,29,1
406,0,0,0,0,3,3,246,25,244.387,23,0
407,0,0,0,0,3,3,118,13,244.387,31,1
408,0,0,0,1,3,4,179,51,244.387,31,0
409,0,0,0,1,3,4,289,36,244.387,30,2
410,0,0,1,0,3,0,260,50,244.387,23,4
411,0,0,0,1,3,1,246,25,244.387,23,0
412,0,0,0,1,5,3,179,51,239.409,31,0
413,0,0,0,1,7,1,260,50,239.409,23,4
414,0,0,0,1,7,1,330,16,239.409,25,0
415,0,0,0,1,10,2,369,17,239.409,25,3
416,0,0,0,1,10,2,248,25,239.409,32,2
417,0,0,0,1,12,0,330,16,239.409,25,0
418,0,0,0,1,12,0,179,51,239.409,31,0
419,0,0,0,1,4,0,118,13,239.409,31,1
420,1,0,0,0,4,2,118,13,239.409,31,1
421,0,0,0,1,4,4,300,26,239.409,25,2
422,0,0,0,1,4,4,260,50,239.409,23,4
423,0,0,0,1,4,0,179,51,239.409,31,0
424,1,0,0,0,4,2,118,10,239.409,28,0
425,1,0,0,0,1,3,235,20,246.074,38,1
426,0,0,0,1,3,6,248,25,246.074,32,2
427,1,0,0,0,8,5,369,17,246.074,25,3
428,0,0,0,1,10,3,179,26,246.074,19,0
429,0,0,0,1,10,3,179,51,246.074,31,0
430,0,0,0,1,11,6,361,52,246.074,27,1
431,0,0,0,1,12,1,260,50,246.074,23,4
432,1,0,0,0,5,0,179,22,246.074,22,2
433,1,0,0,0,5,0,179,22,246.074,22,2
434,0,0,1,0,5,2,228,14,246.074,22,2
435,0,0,0,1,5,2,225,26,246.074,24,1
436,1,0,0,0,5,4,330,16,246.074,25,0
437,0,0,0,1,5,0,179,26,246.074,19,0
438,0,0,0,1,5,0,118,10,246.074,28,0
439,1,0,0,0,5,0,235,11,246.074,29,1
440,0,0,0,1,5,2,179,26,246.074,19,0
441,0,0,0,1,5,5,118,10,253.957,28,0
442,0,0,0,1,5,5,179,51,253.957,31,0
443,0,0,0,1,6,1,118,10,253.957,28,0
444,0,0,0,1,8,6,225,26,253.957,24,1
445,0,0,0,1,9,2,260,50,253.957,23,4
446,0,0,0,0,9,2,179,51,253.957,31,0
447,1,0,0,0,12,2,291,31,253.957,25,1
448,0,0,0,1,12,2,179,51,253.957,31,0
449,0,0,0,1,6,1,246,25,253.957,23,0
450,0,0,0,1,6,0,179,51,253.957,31,0
451,0,0,0,1,6,1,235,20,253.957,38,1
452,0,0,0,1,6,0,179,51,253.957,31,0
453,0,0,0,1,6,2,225,26,253.957,24,1
454,0,0,0,1,6,2,118,13,253.957,31,1
455,1,0,0,0,6,2,179,51,253.957,31,0
456,0,0,1,0,6,2,179,26,253.957,19,0
457,0,0,0,1,6,4,246,25,253.957,23,0
458,1,0,0,0,6,1,330,16,253.957,25,0
459,1,0,0,0,6,1,235,11,253.957,29,1
460,0,0,0,1,6,2,179,26,230.290,19,0
461,0,0,0,1,6,2,225,26,230.290,24,1
462,1,0,0,0,7,4,260,50,230.290,23,4
463,1,0,0,0,10,5,268,11,230.290,25,0
464,0,0,0,1,7,4,330,16,230.290,25,0
465,0,0,0,1,7,4,118,10,230.290,28,0
466,0,0,0,1,7,0,260,50,230.290,23,4
467,0,0,0,1,7,1,118,10,230.290,28,0
468,0,1,0,0,7,0,300,26,230.290,25,2
469,0,0,0,1,7,0,235,29,230.290,33,1
470,0,0,0,1,7,1,246,25,230.290,23,0
471,1,0,0,0,7,1,225,26,230.290,24,1
472,0,0,0,1,7,1,179,51,230.290,31,0
473,0,0,0,1,7,4,118,13,230.290,31,1
474,0,0,0,1,7,4,361,52,230.290,27,1
475,0,0,0,1,7,0,289,36,230.290,30,2
476,0,0,0,1,7,0,235,20,230.290,38,1
477,0,0,0,1,7,1,246,25,230.290,23,0
478,0,0,0,1,7,3,291,31,230.290,25,1
479,0,0,0,1,7,3,279,5,230.290,24,2
480,0,0,0,1,3,2,179,51,249.797,31,0
481,0,0,0,1,7,5,179,22,249.797,22,2
482,0,0,0,1,8,1,246,25,249.797,23,0
483,0,0,0,1,8,1,118,10,249.797,28,0
484,0,0,0,1,8,1,289,36,249.797,30,2
485,0,0,0,1,8,1,235,20,249.797,38,1
486,0,0,0,1,10,6,291,31,249.797,25,1
487,0,0,0,1,8,0,179,51,249.797,31,0
488,0,0,0,1,8,1,179,22,249.797,22,2
489,0,0,0,1,8,3,330,16,249.797,25,0
490,0,0,0,1,8,1,235,11,249.797,29,1
491,0,0,0,1,8,1,246,25,249.797,23,0
492,0,0,0,1,8,1,118,10,249.797,28,0
493,0,0,0,1,8,3,291,31,249.797,25,1
494,0,0,0,1,8,0,260,50,249.797,23,4
495,0,0,0,1,5,1,246,25,261.756,23,0
496,0,0,0,1,5,1,246,25,261.756,23,0
497,0,0,0,1,5,1,118,10,261.756,28,0
498,0,0,0,1,5,1,155,12,261.756,25,2
499,0,0,0,1,7,6,291,31,261.756,25,1
500,0,0,0,1,8,2,179,26,261.756,19,0
501,0,0,0,1,8,2,248,25,261.756,32,2
502,0,0,0,1,11,3,179,51,261.756,31,0
503,0,0,0,1,9,2,225,26,261.756,24,1
504,0,0,0,1,9,0,179,26,261.756,19,0
505,0,0,0,1,9,1,369,17,261.756,25,3
506,0,0,0,1,9,1,361,52,261.756,27,1
507,1,0,0,0,5,2,289,48,284.853,36,0
508,1,0,0,0,5,2,235,16,284.853,25,0
509,0,0,0,1,6,5,246,25,284.853,23,0
510,1,0,0,0,11,4,289,48,284.853,36,0
511,0,0,0,1,11,4,291,31,284.853,25,1
512,0,0,0,1,10,1,118,10,284.853,28,0
513,0,0,0,1,10,3,289,48,284.853,36,0
514,0,0,0,1,10,4,291,31,284.853,25,1
515,0,0,0,1,10,1,225,26,284.853,24,1
516,0,0,0,1,10,1,369,17,284.853,25,3
517,0,0,0,1,10,1,369,17,284.853,25,3
518,0,0,0,1,10,1,225,26,284.853,24,1
519,0,0,0,1,10,1,369,17,284.853,25,3
520,0,0,0,1,10,2,179,51,284.853,31,0
521,1,0,0,0,10,2,228,14,284.853,22,2
522,0,0,0,1,10,2,291,31,284.853,25,1
523,1,0,0,0,10,3,369,17,284.853,25,3
524,1,0,0,0,10,3,225,26,284.853,24,1
525,1,0,0,0,10,4,369,17,284.853,25,3
526,1,0,0,0,10,4,225,26,284.853,24,1
527,0,0,0,1,10,6,189,29,284.853,25,2
528,1,0,0,0,10,6,235,16,284.853,25,0
529,1,0,0,0,10,6,248,25,284.853,32,2
530,0,0,0,0,10,6,225,26,284.853,24,1
531,1,0,0,0,10,1,225,26,284.853,24,1
532,0,0,1,0,7,1,179,51,268.519,31,0
533,0,0,0,1,8,4,118,10,268.519,28,0
534,1,0,0,0,8,4,330,16,268.519,25,0
535,0,0,0,1,10,2,179,51,268.519,31,0
536,1,0,0,0,11,1,118,10,268.519,28,0
537,0,0,0,1,11,2,289,36,268.519,30,2
538,1,0,0,0,11,4,235,16,268.519,25,0
539,0,0,0,1,11,4,225,26,268.519,24,1
540,0,0,0,1,11,1,361,52,268.519,27,1
541,0,0,0,1,11,2,291,31,268.519,25,1
542,1,0,0,0,11,3,118,10,268.519,28,0
543,1,0,0,0,11,3,225,26,268.519,24,1
544,0,0,0,1,11,0,179,51,268.519,31,0
545,0,0,0,1,11,0,118,10,268.519,28,0
546,1,0,0,0,11,1,118,10,268.519,28,0
547,0,0,0,1,11,1,225,26,268.519,24,1
548,0,0,0,0,11,1,291,31,268.519,25,1

In [94]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

## Standardize the data

In [95]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()
# the object we jsut created will take the mean and divide by the standard deviation for each point in our data variablewise

In [96]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [97]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [98]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.80633129,
         0.76743118,  0.88046927],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.80633129,
         1.00263338, -0.01928035],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.80633129,
         1.00263338, -0.91902997],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.85378935,
        -0.40857982, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.85378935,
        -0.40857982, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.85378935,
        -0.40857982, -0.01928035]])

In [99]:
scaled_inputs.shape

(700, 11)

## OverFitting & Underfitting

Overfitting occurs when the model learns to predict the data so well that when appplied i real life o new data, it fails misserably.One way to deal withover fitting is by hiding a small part of the data set from the algorithm

## Split the data

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, target, train_size=0.8, random_state=20)

In [102]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)

In [103]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)

## The Logistoc Regresson Model

In [104]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [105]:
reg = LogisticRegression()

In [106]:
reg.fit(x_train, y_train)

/home/dangote/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [107]:
round(reg.score(x_train, y_train), 2)*100

76.0

## Manually check accuracy

In [108]:
# Find model putput and compare them with the target
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0])

In [109]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [110]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True])

In [111]:
np.sum(model_outputs==y_train)

428

In [112]:
#Accuracy = correct predictions/observation
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7642857142857142

## Finding the intercept and coeeficient

In [113]:
reg.intercept_

array([-0.22672598])

In [114]:
reg.coef_

array([[ 2.01820689,  0.30458028,  1.46074976,  1.27443801,  0.01835844,
        -0.08959537,  0.59063433, -0.01360498, -0.01012292,  0.28283932,
         0.39688753]])

In [115]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Children'],
      dtype=object)

In [116]:
feature_name =unscaled_inputs.columns.values

In [117]:
sumry_table = pd.DataFrame(columns=["Feature Name"], data=feature_name)

sumry_table['coefficient'] = np.transpose(reg.coef_)

sumry_table

               Feature Name  coefficient
0                  Reason_1     2.018207
1                  Reason_2     0.304580
2                  Reason_3     1.460750
3                  Reason_4     1.274438
4              Month Values     0.018358
5           Day of the Week    -0.089595
6    Transportation Expense     0.590634
7          Distance to Work    -0.013605
8   Daily Work Load Average    -0.010123
9           Body Mass Index     0.282839
10                 Children     0.396888

In [118]:
sumry_table.index = sumry_table.index +1
sumry_table.loc[0] = ['Intercept', reg.intercept_[0]]
sumry_table= sumry_table.sort_index()
sumry_table

               Feature Name  coefficient
0                 Intercept    -0.226726
1                  Reason_1     2.018207
2                  Reason_2     0.304580
3                  Reason_3     1.460750
4                  Reason_4     1.274438
5              Month Values     0.018358
6           Day of the Week    -0.089595
7    Transportation Expense     0.590634
8          Distance to Work    -0.013605
9   Daily Work Load Average    -0.010123
10          Body Mass Index     0.282839
11                 Children     0.396888

## Interpreting the coefficients
The closer the weights to 0, the smaller to the weight

In [119]:
sumry_table['Odds_ratio'] = np.exp(sumry_table.coefficient)

In [120]:
sumry_table

               Feature Name  coefficient  Odds_ratio
0                 Intercept    -0.226726    0.797139
1                  Reason_1     2.018207    7.524820
2                  Reason_2     0.304580    1.356056
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
5              Month Values     0.018358    1.018528
6           Day of the Week    -0.089595    0.914301
7    Transportation Expense     0.590634    1.805133
8          Distance to Work    -0.013605    0.986487
9   Daily Work Load Average    -0.010123    0.989928
10          Body Mass Index     0.282839    1.326892
11                 Children     0.396888    1.487189

In [121]:
# we sort the valeus i respect to a given column
sumry_table.sort_values('Odds_ratio', ascending=False)

               Feature Name  coefficient  Odds_ratio
1                  Reason_1     2.018207    7.524820
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
7    Transportation Expense     0.590634    1.805133
11                 Children     0.396888    1.487189
2                  Reason_2     0.304580    1.356056
10          Body Mass Index     0.282839    1.326892
5              Month Values     0.018358    1.018528
9   Daily Work Load Average    -0.010123    0.989928
8          Distance to Work    -0.013605    0.986487
6           Day of the Week    -0.089595    0.914301
0                 Intercept    -0.226726    0.797139

A feature is not particularly important;

- if its coefficient is around 0
- if its odds ratio is around 1

Note, when we standardized variables, it is advisable not to standardize the dummies. For that, we'll have to eedit our code where we standardized our variables.

In [122]:
## Creating a Custom SCaler to Standardize Only Numeric Features
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, x, y=None):
        self.scaler.fit(x[self.columns], y)
        self.mean_ = np.mean(x[self.columns])
        self.var_ =np.var(x[self.columns])
        return self
    
    def transform(self, x, y=None, copy=None):
        init_col_order = x.columns
        x_scaled = pd.DataFrame(self.scaler.transform(x[self.columns]), columns=self.columns)
        x_not_scaled = x.loc[:, ~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled, x_scaled], axis=1)[init_col_order]

In [123]:
# We create a new varibale that hold the columns we need to scale
# We refer back to our #unscaled_inputs columns

unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Children'],
      dtype=object)

In [124]:
columns_to_scale = ['Month Values','Day of the Week', 'Transportation Expense', 'Distance to Work',
        'Daily Work Load Average', 'Body Mass Index','Children',]

In [125]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [126]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Values', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work',
                      'Daily Work Load Average', 'Body Mass Index',
                      'Children'],
             copy=None, with_mean=None, with_std=None)

In [127]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [128]:
scaled_inputs.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Values,Day of the Week,Transportation Expense,Distance to Work,Daily Work Load Average,Body Mass Index,Children
0,0,0,0,1,0.030796,-0.800950,1.005844,0.412816,-0.806331,0.767431,0.880469
1,0,0,0,0,0.030796,-0.800950,-1.574681,-1.141882,-0.806331,1.002633,-0.019280
2,0,0,0,1,0.030796,-0.232900,-0.654143,1.426749,-0.806331,1.002633,-0.919030
3,1,0,0,0,0.030796,0.335149,0.854936,-1.682647,-0.806331,-0.643782,0.880469
4,0,0,0,1,0.030796,0.335149,1.005844,0.412816,-0.806331,0.767431,0.880469

## Interpreting the Important Coefficients

In [129]:
# we sort the valeus i respect to a given column
# remember that the further away from 0 a coeffcient is, the bigger its importance 
sumry_table.sort_values('Odds_ratio', ascending=False)

               Feature Name  coefficient  Odds_ratio
1                  Reason_1     2.018207    7.524820
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
7    Transportation Expense     0.590634    1.805133
11                 Children     0.396888    1.487189
2                  Reason_2     0.304580    1.356056
10          Body Mass Index     0.282839    1.326892
5              Month Values     0.018358    1.018528
9   Daily Work Load Average    -0.010123    0.989928
8          Distance to Work    -0.013605    0.986487
6           Day of the Week    -0.089595    0.914301
0                 Intercept    -0.226726    0.797139

From above table, we observe that the Reasons variables are of higher importance to our model, Day of the week, Age, Pets, Education all have poor valeus not too far away from 0. This indicates how less important they affect our prediction.

## Simplifying the model(Backward Elimination)

We'll use backward elimination toremove all features that have close to no contribution to our model.

In [130]:
# we manuay removed unwanted columns from the columns to scale variable
sumry_table.sort_values('Odds_ratio', ascending=False)

               Feature Name  coefficient  Odds_ratio
1                  Reason_1     2.018207    7.524820
3                  Reason_3     1.460750    4.309189
4                  Reason_4     1.274438    3.576691
7    Transportation Expense     0.590634    1.805133
11                 Children     0.396888    1.487189
2                  Reason_2     0.304580    1.356056
10          Body Mass Index     0.282839    1.326892
5              Month Values     0.018358    1.018528
9   Daily Work Load Average    -0.010123    0.989928
8          Distance to Work    -0.013605    0.986487
6           Day of the Week    -0.089595    0.914301
0                 Intercept    -0.226726    0.797139

## Testing The Model

In [131]:
round(reg.score(x_test, y_test), 2)*100

74.0

In [132]:
# A better way to view our model predicted output is by printing out the probabilities
# The first column =0 probality, second =1 probaities
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.78262815, 0.21737185],
       [0.60353624, 0.39646376],
       [0.45692546, 0.54307454],
       [0.80370109, 0.19629891],
       [0.07634123, 0.92365877],
       [0.2980815 , 0.7019185 ],
       [0.24126161, 0.75873839],
       [0.06804446, 0.93195554],
       [0.7474479 , 0.2525521 ],
       [0.78418216, 0.21581784],
       [0.38264536, 0.61735464],
       [0.24541156, 0.75458844],
       [0.06329931, 0.93670069],
       [0.61103277, 0.38896723],
       [0.1431606 , 0.8568394 ],
       [0.56472246, 0.43527754],
       [0.40469079, 0.59530921],
       [0.43192104, 0.56807896],
       [0.23979167, 0.76020833],
       [0.04798899, 0.95201101],
       [0.72326237, 0.27673763],
       [0.7955474 , 0.2044526 ],
       [0.46077679, 0.53922321],
       [0.48065635, 0.51934365],
       [0.18678878, 0.81321122],
       [0.74213657, 0.25786343],
       [0.539073  , 0.460927  ],
       [0.88751763, 0.11248237],
       [0.2211046 , 0.7788954 ],
       [0.78714473, 0.21285527],
       [0.58081072, 0.41918928],
       [0.24986395, 0.75013605],
       [0.32006405, 0.67993595],
       [0.38045521, 0.61954479],
       [0.7955474 , 0.2044526 ],
       [0.43500791, 0.56499209],
       [0.734472  , 0.265528  ],
       [0.24589373, 0.75410627],
       [0.46357453, 0.53642547],
       [0.44347016, 0.55652984],
       [0.77244193, 0.22755807],
       [0.56016741, 0.43983259],
       [0.75139335, 0.24860665],
       [0.91128724, 0.08871276],
       [0.11248342, 0.88751658],
       [0.35190548, 0.64809452],
       [0.29076658, 0.70923342],
       [0.77141469, 0.22858531],
       [0.75678805, 0.24321195],
       [0.80902709, 0.19097291],
       [0.48376738, 0.51623262],
       [0.94521763, 0.05478237],
       [0.31541701, 0.68458299],
       [0.76260767, 0.23739233],
       [0.13480013, 0.86519987],
       [0.55059412, 0.44940588],
       [0.04471856, 0.95528144],
       [0.74746709, 0.25253291],
       [0.93033958, 0.06966042],
       [0.93276281, 0.06723719],
       [0.26978631, 0.73021369],
       [0.35255596, 0.64744404],
       [0.75378876, 0.24621124],
       [0.17499843, 0.82500157],
       [0.70261021, 0.29738979],
       [0.78239868, 0.21760132],
       [0.99100617, 0.00899383],
       [0.74507832, 0.25492168],
       [0.22132666, 0.77867334],
       [0.60550243, 0.39449757],
       [0.74271251, 0.25728749],
       [0.92446177, 0.07553823],
       [0.0995901 , 0.9004099 ],
       [0.46771728, 0.53228272],
       [0.39999013, 0.60000987],
       [0.78714473, 0.21285527],
       [0.20891504, 0.79108496],
       [0.18772928, 0.81227072],
       [0.27415007, 0.72584993],
       [0.20366758, 0.79633242],
       [0.72679589, 0.27320411],
       [0.98182483, 0.01817517],
       [0.7589939 , 0.2410061 ],
       [0.26894743, 0.73105257],
       [0.49797903, 0.50202097],
       [0.88876151, 0.11123849],
       [0.31599168, 0.68400832],
       [0.49238935, 0.50761065],
       [0.95049116, 0.04950884],
       [0.25952412, 0.74047588],
       [0.7830588 , 0.2169412 ],
       [0.89924358, 0.10075642],
       [0.76149575, 0.23850425],
       [0.7899683 , 0.2100317 ],
       [0.80091068, 0.19908932],
       [0.11837033, 0.88162967],
       [0.7963721 , 0.2036279 ],
       [0.26468182, 0.73531818],
       [0.7878882 , 0.2121118 ],
       [0.74918299, 0.25081701],
       [0.40982799, 0.59017201],
       [0.24044659, 0.75955341],
       [0.29491762, 0.70508238],
       [0.33051067, 0.66948933],
       [0.47927787, 0.52072213],
       [0.47875164, 0.52124836],
       [0.79930416, 0.20069584],
       [0.13525531, 0.86474469],
       [0.25723834, 0.74276166],
       [0.87456926, 0.12543074],
       [0.98201148, 0.01798852],
       [0.08216362, 0.91783638],
       [0.37537526, 0.62462474],
       [0.57328884, 0.42671116],
       [0.44077855, 0.55922145],
       [0.40553993, 0.59446007],
       [0.24165903, 0.75834097],
       [0.11487636, 0.88512364],
       [0.36551433, 0.63448567],
       [0.70119808, 0.29880192],
       [0.79866721, 0.20133279],
       [0.87936076, 0.12063924],
       [0.2381267 , 0.7618733 ],
       [0.48824312, 0.51175688],
       [0.77467826, 0.22532174],
       [0.64368226, 0.35631774],
       [0.79816023, 0.20183977],
       [0.87439279, 0.12560721],
       [0.32836299, 0.67163701],
       [0.71099742, 0.28900258],
       [0.39327353, 0.60672647],
       [0.7893138 , 0.2106862 ],
       [0.79435093, 0.20564907],
       [0.63480949, 0.36519051],
       [0.74872812, 0.25127188],
       [0.43773533, 0.56226467],
       [0.44057601, 0.55942399],
       [0.63809807, 0.36190193],
       [0.76125255, 0.23874745],
       [0.43715336, 0.56284664]])

In [133]:
predicted_proba.shape

(140, 2)

In [134]:
# Let's check the result of excessive absenteeism
predicted_proba[:, 1]

array([0.21737185, 0.39646376, 0.54307454, 0.19629891, 0.92365877,
       0.7019185 , 0.75873839, 0.93195554, 0.2525521 , 0.21581784,
       0.61735464, 0.75458844, 0.93670069, 0.38896723, 0.8568394 ,
       0.43527754, 0.59530921, 0.56807896, 0.76020833, 0.95201101,
       0.27673763, 0.2044526 , 0.53922321, 0.51934365, 0.81321122,
       0.25786343, 0.460927  , 0.11248237, 0.7788954 , 0.21285527,
       0.41918928, 0.75013605, 0.67993595, 0.61954479, 0.2044526 ,
       0.56499209, 0.265528  , 0.75410627, 0.53642547, 0.55652984,
       0.22755807, 0.43983259, 0.24860665, 0.08871276, 0.88751658,
       0.64809452, 0.70923342, 0.22858531, 0.24321195, 0.19097291,
       0.51623262, 0.05478237, 0.68458299, 0.23739233, 0.86519987,
       0.44940588, 0.95528144, 0.25253291, 0.06966042, 0.06723719,
       0.73021369, 0.64744404, 0.24621124, 0.82500157, 0.29738979,
       0.21760132, 0.00899383, 0.25492168, 0.77867334, 0.39449757,
       0.25728749, 0.07553823, 0.9004099 , 0.53228272, 0.60000987,
       0.21285527, 0.79108496, 0.81227072, 0.72584993, 0.79633242,
       0.27320411, 0.01817517, 0.2410061 , 0.73105257, 0.50202097,
       0.11123849, 0.68400832, 0.50761065, 0.04950884, 0.74047588,
       0.2169412 , 0.10075642, 0.23850425, 0.2100317 , 0.19908932,
       0.88162967, 0.2036279 , 0.73531818, 0.2121118 , 0.25081701,
       0.59017201, 0.75955341, 0.70508238, 0.66948933, 0.52072213,
       0.52124836, 0.20069584, 0.86474469, 0.74276166, 0.12543074,
       0.01798852, 0.91783638, 0.62462474, 0.42671116, 0.55922145,
       0.59446007, 0.75834097, 0.88512364, 0.63448567, 0.29880192,
       0.20133279, 0.12063924, 0.7618733 , 0.51175688, 0.22532174,
       0.35631774, 0.20183977, 0.12560721, 0.67163701, 0.28900258,
       0.60672647, 0.2106862 , 0.20564907, 0.36519051, 0.25127188,
       0.56226467, 0.55942399, 0.36190193, 0.23874745, 0.56284664])

## Save The Model
We'll use **pickle** to save our model. Pickle is python module used to convert a python object into a character stream

In [135]:
import pickle

In [136]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [137]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)

## Using the Absenteeism module

In [138]:
from absenteeism_module import *

In [139]:
pd.read_csv('Absenteeism_new_data.csv').head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0

In [140]:
model = absenteeism_model('model', 'scaler')

In [141]:
model.load_and_clean_data('Absenteeism_new_data.csv')

KeyError: "['Daily Work Load Average', 'Month Values', 'Distance to Work', 'Day of the Week'] not in index"

In [ ]:
model.predicted_outputs()